Import('env', 'common', 'msgq')

cereal_dir = Dir('.')
gen_dir = Dir('gen')
schema_dir = Dir('gen/capnp')

# Build cereal
schema_files = ['log.capnp', 'car.capnp', 'legacy.capnp', 'custom.capnp']
schema_sources = {
  'log.capnp': 'log.capnp',
  'car.capnp': '#opendbc_repo/opendbc/car/car.capnp',
  'legacy.capnp': 'legacy.capnp',
  'custom.capnp': 'custom.capnp',
}
generated_schemas = [
  env.Command(f'gen/capnp/{schema}', source, Copy('$TARGET', '$SOURCE'))
  for schema, source in schema_sources.items()
]
include_schema = env.Command('gen/capnp/include/c++.capnp', 'include/c++.capnp', Copy('$TARGET', '$SOURCE'))
capnp_outputs = env.Command([f'gen/cpp/{s}.c++' for s in schema_files] + [f'gen/cpp/{s}.h' for s in schema_files],
                            [f'gen/capnp/{s}' for s in schema_files],
                            f"capnpc --src-prefix={schema_dir.path} $SOURCES -o c++:{gen_dir.path}/cpp/")
Depends(capnp_outputs, generated_schemas + [include_schema])

cereal = env.Library('cereal', [f'gen/cpp/{s}.c++' for s in schema_files])

# Build messaging
services_h = env.Command(['services.h'], ['services.py'], 'python3 ' + cereal_dir.path + '/services.py > $TARGET')
env.Program('messaging/bridge', ['messaging/bridge.cc', 'messaging/msgq_to_zmq.cc'], LIBS=[msgq, common, 'pthread'])

socketmaster = env.Library('socketmaster', ['messaging/socketmaster.cc'])

Export('cereal', 'socketmaster')
